### ISSUE TITLE
Driver does not compile with ARMCC6

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/wizfi310-driver#1]
https://github.com/ARMmbed/wizfi310-driver/blob/master/WizFi310Interface.cpp#L166-L168

The function probably should at least

return 0;

to be valid for int-type function, or change to void-type.

ARMCC6 complains:

```
00:03:31.887 [ERROR] ./easy-connect/wizfi310-driver/WizFi310Interface.cpp:168:1: error: control reaches end of non-void function [-Werror,-Wreturn-type]
00:03:31.887 }
00:03:31.887 ^
00:03:31.887 1 error generated.
```

**Comment by teetak01** [comment]
@kaizen8501 can you check this?

**Comment by kaizen8501** [comment]
Hi @teetak01 

Thank you for your opinion. I modified source code.

**Comment by teetak01** [comment]
Thanks. I think I need to add some build-verification to easy-connect and we can then try to update the driver there.

**Comment by teetak01** [comment]
Closing as fixed. @kaizen8501 could you make a PR to easy-connect, or is it fine if I update the driver there myself?
