### ISSUE TITLE
[HW] WIFI_RESET triggers a general reset.

### ISSUE THREAD

**Issue by ithinuel** [ARMmbed/wizfi310-driver#15]
This is confirmed on :
- NUCLEO_L476
- DISCO_F469
- NUCLEO_L4R5

This prevents us from use D9 to generate a reset of the module.

**Comment by wpgnss** [comment]
Thanks @ithinuel 

we checked  the problem you mentioned.
and our HW engineer is reviewing this issue.

WizFi310 shield is designed to reset the module itself using MCU Reset.
We are looking for the exact cause, and we will apply this issue on next version.
now, we suggest you to remove D1 to use D9 to generate a reset of the module.

![image](https://user-images.githubusercontent.com/10935843/54403563-d4b39380-4713-11e9-8086-8b4f3842758d.png)


Thanks.

**Comment by wpgnss** [comment]
> This is confirmed on :
> 
> * NUCLEO_L476
> * DISCO_F469
> * NUCLEO_L4R5
> 
> This prevents us from use D9 to generate a reset of the module.

Thanks @ithinuel

we checked the problem you mentioned.
and our HW engineer is reviewing this issue.

WizFi310 shield is designed to reset the module itself using MCU Reset.
We are looking for the exact cause, and we will apply this issue on next version.
now, we suggest you to remove D1 to use D9 to generate a reset of the module.

Thanks.

**Comment by wpgnss** [comment]
if you want to use D9 without WiFi RST function.
you should turn off the SW5-3 on the shield.
