### ISSUE TITLE
The module stops sending a packet before the end.

### ISSUE THREAD

**Issue by ithinuel** [ARMmbed/wizfi310-driver#16]
This tends to occur when the flow it being throttled by flow control.
See this logic analyser capture at timestamp `62.673s` : [wizfi310_stops_sending_62.673.zip](https://github.com/ARMmbed/wizfi310-driver/files/2965635/wizfi310_stops_sending_62.673.zip)

**Comment by wpgnss** [comment]
could you please give me a source code of the test scenario?

let me know detailed. does your problem mean 0.32ms in the below?
![image](https://user-images.githubusercontent.com/10935843/54402989-bba9e300-4711-11e9-9764-b492af0b25a5.png)

It could be delayed on TCP network.
or Other high-priority tasks are being handled in the module.

Thanks.

**Comment by ithinuel** [comment]
Hi,
Thanks for looking at this and sorry for the last response.
I will update this Issue as soon as I can spare some time to create a minimalist replication example.

In the case of this trace,
The frame ending at 62.673 (starting at 60.700) is expected to be 1500 bytes long (of payload) but stops after 1251 bytes.
This prevents a driver to properly extract the frame. analysing the whole frame is not an option as it would open the door to false positives.
