### ISSUE TITLE
CTS/RTS should be supported

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/wizfi310-driver#2]
Can you clarify if the CTS/RTS (flow control) could be supported with the driver or not?

Currently - looking at the code - it seems the pins are non-connected, though the HW does have them (and thus I assume the HW itself supports them).

Ref:

https://github.com/ARMmbed/wizfi310-driver/blob/e78ec79cf496133c2afe4196d953b69af5b3c6ab/WizFi310Interface.h#L44-L47

Practice has shown that w/o HW flow control the reliability of the data transmissions leaves something to hope for (not that I would claim to have found any issues with WizFi310 as of yet, as we have not done any heavy stress testing with it).

**Comment by kaizen8501** [comment]
Hi @JanneKiiskila

Actually, previous WizFi310 mbed library has flow-control function but it looks like new mbed library doesn't want flow-control function so I removed it.
( That 4 lines code, I should have erased that but I did not. That's my fault. )

If that is necessary, we can add flow-control function in WizFi310-driver.
Please let me know your opinion.^^ ( If that is not necessary, I will remove that codes in WizFi310-driver )

Thank you.
