### ISSUE TITLE
[HW] When coupled with an NRF52840_DK, the uart signal do not go back to GND when set to logic 0.

### ISSUE THREAD

**Issue by ithinuel** [ARMmbed/wizfi310-driver#20]
When couple with the NRF52840_DK,

the UART signals stay at around 0.6V instead of being 0V.

Also, even though it does not seem to be a problem for the Wifi module, as you can see on the previous capture, the serial signal do not look as squared as one would expect.
![image](https://user-images.githubusercontent.com/4605303/55325747-d7d1b200-547d-11e9-8bf4-5f4b5d2dabd2.png)

Finally, the measurement on the response from the wifi module show that the byte do not make it through the level shifter.

![image](https://user-images.githubusercontent.com/4605303/55325611-845f6400-547d-11e9-9ea6-8db12734eb7d.png)

**PS:** Note we changed R82 from its initial value of 330KOhm to ~390KOhm (actually 620K and 910K in parallel). So the actually voltage you will see might be lower (~2.9V).

**Comment by wpgnss** [comment]
I will notice it to HW engineer.
