### ISSUE TITLE
[SW] The module may not send [OK] nor [ERROR] before the greeting message.

### ISSUE THREAD

**Issue by ithinuel** [ARMmbed/wizfi310-driver#21]
This capture shows a case were `OK` are missing after commands that do trigger resets :
```
69.419252 Command: "AT+MFDEF=FR\r"
69.425297 Response: "WizFi310 Version 1.0.3.2 (WIZnet Co.Ltd)\r\n"
69.426221 Command: "AT+MECHO=0\r"
70.675655 Response: "[OK]\r\n"
70.677692 Command: "AT+USET=115200,N,8,1,HW\r"
71.709026 Response: "WizFi310 Version 1.0.3.2 (WIZnet Co.Ltd)\r\n"
```
[wizfi310_ok_not_sent.zip](https://github.com/ARMmbed/wizfi310-driver/files/3029631/wizfi310_ok_not_sent.zip)

**Comment by wpgnss** [comment]
Hi @ithinuel 
> ```
> 69.419252 Command: "AT+MFDEF=FR\r"
> 69.425297 Response: "WizFi310 Version 1.0.3.2 (WIZnet Co.Ltd)\r\n"
> 69.426221 Command: "AT+MECHO=0\r"
> 70.675655 Response: "[OK]\r\n"
> 70.677692 Command: "AT+USET=115200,N,8,1,HW\r"
> 71.709026 Response: "WizFi310 Version 1.0.3.2 (WIZnet Co.Ltd)\r\n"
> ```

This is a normal steps we planed.
most of AT commands have responses except for several AT commands.
AT+USET is one of them. this command occurs immediately module reset after UART setting.

**Comment by ithinuel** [comment]
Hi @wpgnss , I would have agreed if this behaviour was consistent but it is not.
On the attached trace, you can see at timestamp 22.415 an `AT+USET` followed by an `[OK]` and a reset while at 70.6756 `AT+USET` has the reset without `[OK]`.

**Comment by wpgnss** [comment]
I checked again and there was my mistake.
The USET command has an OK response.

> WizFi310 Version 1.0.3.4 (WIZnet Co.Ltd)
> at+uset=115200,N,8,1,N
> [OK]
> WizFi310 Version 1.0.3.4 (WIZnet Co.Ltd)

if the module was connected to TCP Server.
> at+scon=o,tcn,11.00.000.99,6000,,0
> [OK]
>
> [CONNECT 0]
> {0,11.00.000.99,6000,4}TEST
> at+uset=115200,N,8,1,HW
> [OK]
>
> [DISCONNECT 0]
>
> [Link-Down Event]
> WizFi310 Version 1.0.3.4 (WIZnet Co.Ltd)

**So it seems normal behavior at 22.415s.** i need lots of information to estimate the results.

why did you used AT+MFDEF=FR command? this command will set all environment to basic.

**Comment by ithinuel** [comment]
I used this command to reset the device to its basic and known configuration.
