### ISSUE TITLE
os.mbed.com has stale code

### ISSUE THREAD

**Issue by dreemkiller** [ARMmbed/wizfi310-driver#3]
When googling for WizFi310 and Mbed OS, the first result that comes up is: https://os.mbed.com/teams/WIZnet/code/WizFi310Interface/

However, the code on that site is not current, and does not work out of the box (I have to specifically tell the mbed CLI to fetch MBed OS 5.7).
The code on the os.mbed.com site probably needs to be updated, removed, or the instructions clarified.

**Comment by kaizen8501** [comment]
Hi @dreemkiller 
I'm sorry for the confusion. we used that library before mbed OS5 is not released.
That time mbed OS5 was preparing so I modified that library's information.
[https://os.mbed.com/teams/WIZnet/code/WizFi310Interface/](https://os.mbed.com/teams/WIZnet/code/WizFi310Interface/)
