### ISSUE TITLE
Please implement get_default_instance

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/wizfi310-driver#9]
With Mbed OS 5.10 the network interfaces changed a bit, please implement `get_default_instance()` implementation for this driver, too.

Example can be found from within Mbed OS in the [ESP8266 driver](https://github.com/ARMmbed/mbed-os/blob/mbed-os-5.10/components/wifi/esp8266-driver/ESP8266Interface.cpp#L579-L586).

**Comment by 0xc0170** [comment]
This is still valid. As we are now at 5.11, please test this driver with latest version

**Comment by wpgnss** [comment]
Thank you for your contribution. Applied in a commit #14.
